matrix:
  include:
    - os: linux
      node_js:
        - "12"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=12"
        - DEPLOYJS=1
    - os: linux
      node_js:
        - "11"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=11"
        - DEPLOYJS=1
    - os: linux
      node_js:
        - "10"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=10"
        - DEPLOYJS=1
    - os: linux
      node_js:
        - "9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=9"
    - os: linux
      node_js:
        - "8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=8"
    - os: linux
      node_js:
        - "6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && NODEJS=6"
    - os: osx
      osx_image: xcode8
      node_js:
        - "12"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=12"
    - os: osx
      osx_image: xcode8
      node_js:
        - "11"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=11"
    - os: osx
      osx_image: xcode8
      node_js:
        - "10"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=10"
    - os: osx
      osx_image: xcode8
      node_js:
        - "9"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=9"
    - os: osx
      osx_image: xcode8
      node_js:
        - "8"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=8"
    - os: osx
      osx_image: xcode8
      node_js:
        - "6"
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7 && NODEJS=6"
language: node_js
sudo: required
before_install:
  # get commit message
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  # put local node-pre-gyp on PATH
  - export PATH=./node_modules/.bin/:$PATH
  # put global node-gyp on PATH
  - npm install node-gyp -g
  # figure out if we should publish
  - PUBLISH_BINARY=false
  # if we are building a tag then publish
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  # or if we put [publish binary] in the commit message
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;
  # Run your build commands next
  - chmod +x ./install-dependencies.sh
  - ./install-dependencies.sh

install:
- npm install
- npm run build
- npm test

before_script:
# if publishing, do it
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi;
# cleanup
- node-pre-gyp clean
- node-gyp clean

script:
- npm install codecov -g
# if publishing, test installing from remote
- INSTALL_RESULT=0
- if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi;
# if install returned non zero (errored) then we first unpublish and then call false so travis will bail at this line
- if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";node-pre-gyp unpublish;false; fi
# If success then we arrive here so lets clean up
- node-pre-gyp clean

after_success:
# if success then query and display all published binaries
- node-pre-gyp info
- codecov

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $DEPLOYJS = 1